# Generated by Django 4.2.18 on 2025-01-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcns', '0002_remove_genedata_gene_id_remove_genedata_srr11484242_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
    ]
