# Generated by Django 4.2.18 on 2025-02-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcns', '0003_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gene', models.CharField(max_length=100)),
                ('mRNA', models.CharField(max_length=100)),
                ('Pfma_acc', models.CharField(max_length=100)),
                ('Pfma_name', models.CharField(max_length=100)),
                ('Pfma_type', models.CharField(max_length=100)),
                ('evalue', models.FloatField(default=0.0)),
            ],
        ),
    ]
