# Generated by Django 4.2.18 on 2025-02-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcns', '0004_pfam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gontology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gene', models.CharField(max_length=100)),
                ('mRNA', models.CharField(max_length=100)),
                ('GO_acc', models.CharField(max_length=100)),
                ('GO_name', models.CharField(max_length=100)),
                ('GO_type', models.CharField(max_length=100)),
            ],
        ),
    ]
