# Generated by Django 4.2.18 on 2025-02-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcns', '0005_gontology'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gene1', models.CharField(max_length=100)),
                ('Gene2', models.CharField(max_length=100)),
                ('MRank', models.FloatField(default=0.0)),
            ],
        ),
    ]
