# Generated by Django 4.2.18 on 2025-04-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcns', '0006_mutualrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gene', models.CharField(max_length=100)),
                ('Note', models.CharField(max_length=100)),
            ],
        ),
    ]
