# Generated by Django 4.2.18 on 2025-04-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcns', '0007_genenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genenote',
            name='Note',
            field=models.CharField(max_length=500),
        ),
    ]
