# Generated by Django 4.2.18 on 2025-10-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcns', '0009_genedata_srr28195857_genedata_srr28195864_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genedata',
            name='SRR33960832',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='genedata',
            name='SRR33960833',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='genedata',
            name='SRR33960834',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='genedata',
            name='SRR33960835',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='genedata',
            name='SRR33960836',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='genedata',
            name='SRR33960837',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='genedata',
            name='SRR33960838',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='genedata',
            name='SRR33960839',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='genedata',
            name='SRR33960840',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='genedata',
            name='SRR33960841',
            field=models.FloatField(default=0.0),
        ),
    ]
